name: notebooks-env
channels:
- conda-forge
- defaults
dependencies:
- jupyter_contrib_core=0.3.1=py36_0
- jupyter_latex_envs=1.3.8.2=py36_1
- jupyter_nbextensions_configurator=0.2.5=py36_0
- nbconvert=5.2.1=py36_0
- nbformat=4.3.0=py36_0
- notebook=5.0.0=py36_0
- numpy=1.13.0=py36_0
- scipy=0.19.0=np113py36_0
- matplotlib=2.0.2=np113py36_0
- pip:
  - ipython-genutils==0.2.0
  - jupyter-client==5.0.1
  - jupyter-console==5.1.0
  - jupyter-contrib-core==0.3.1
  - jupyter-core==4.3.0
  - jupyter-latex-envs==1.3.8.2
  - jupyter-nbextensions-configurator==0.2.5
  - prompt-toolkit==1.0.14
